services:
  - type: web
    name: X-HUB-BOT
    repo: https://github.com/MAD-MAX77/Devux-MD.git
    branch: main
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: RENDER_APP_NAME
        sync: false
        required: true
      - key: RENDER_API
        sync: false
        required: true
      - key: DATABASE_URL
        sync: false
        required: true
        
